### ISSUE TITLE
InvalidPlistException: Encountered integer longer than 16 bytes.

### ISSUE THREAD

**Issue by paulr4** [wooster/biplist#10]
I'm having trouble with the following data; when trying to parse it with biplist I get the error 'InvalidPlistException: Encountered integer longer than 16 bytes.'

I don't think the data is bad (it works in the program that generated it) so I'm wondering if there's a problem in the way biplist handles it?

--------------------------

bplist00\xd4\x01\x02\x03\x04\x05}~\x7fX$objectsY$archiverX$versionT$top\xaf\x10\x13\x06\x07\x16\x1b"\'.3:?FKRW^cjovU$null\xd3\x08\t\n\x0b\x10\x15WNS.keysZNS.objectsV$class\xa4\x0c\r\x0e\x0f\x80\x02\x80\x04\x80\x06\x80\x08\xa4\x11\x12\x13\x14\x80\n\x80\x0c\x80\x0e\x80\x10\x80\x12\xd2\x17\x18\x19\x1aYNS.stringV$classXfullname\x80\x03\xd2\x1c\x1d\x1e!X$classesZ$classname\xa2\x1f

 XNSStringXNSObjectXNSString\xd2#$%&YNS.stringV$classWaddress\x80\x05\xd2()*-X$classesZ$classname\xa2+,XNSStringXNSObjectXNSString\xd2/012YNS.stringV$classUphone\x80\x07\xd24569X$classesZ$classname\xa278XNSStringXNSObjectXNSString\xd2;<=>YNS.stringV$classUemail\x80\t\xd2@ABEX$classesZ$classname\xa2CDXNSStringXNSObjectXNSString\xd2GHIJYNS.stringV$class[Test Client\x80\x0b\xd2LMNQX$classesZ$classname\xa2OPXNSStringXNSObjectXNSString\xd2STUVYNS.stringV$class^123 ABC Street\x80\r\xd2XYZ]X$classesZ$classname\xa2[\\XNSStringXNSObjectXNSString\xd2_`abYNS.stringV$classT1234\x80\x0f\xd2defiX$classesZ$classname\xa2ghXNSStringXNSObjectXNSString\xd2klmnYNS.stringV$class]test@test.com\x80\x11\xd2pqruX$classesZ$classname\xa2stXNSStringXNSObjectXNSString\xd2wxy|X$classesZ$classname\xa2z{\\NSDictionaryXNSObject\\NSDictionary_\x10\x0fNSKeyedArchiver\x12\x00\x01\x86\xa0\xd1\x80\x81Troot\x80\x01\x00\x08\x00\x11\x00\x1a\x00$\x00-\x002\x00H\x00N\x00U\x00]\x00h\x00o\x00t\x00v\x00x\x00z\x00|\x00\x81\x00\x83\x00\x85\x00\x87\x00\x89\x00\x8b\x00\x90\x00\x9a\x00\xa1\x00\xaa\x00\xac\x00\xb1\x00\xba\x00\xc5\x00\xc8\x00\xd1\x00\xda\x00\xe3\x00\xe8\x00\xf2\x00\xf9\x01\x01\x01\x03\x01\x08\x01\x11\x01\x1c\x01\x1f\x01(\x011\x01:\x01?\x01I\x01P\x01V\x01X\x01]\x01f\x01q\x01t\x01}\x01\x86\x01\x8f\x01\x94\x01\x9e\x01\xa5\x01\xab\x01\xad\x01\xb2\x01\xbb\x01\xc6\x01\xc9\x01\xd2\x01\xdb\x01\xe4\x01\xe9\x01\xf3\x01\xfa\x02\x06\x02\x08\x02\r\x02\x16\x02!\x02$\x02-\x026\x02?\x02D\x02N\x02U\x02d\x02f\x02k\x02t\x02\x7f\x02\x82\x02\x8b\x02\x94\x02\x9d\x02\xa2\x02\xac\x02\xb3\x02\xb8\x02\xba\x02\xbf\x02\xc8\x02\xd3\x02\xd6\x02\xdf\x02\xe8\x02\xf1\x02\xf6\x03\x00\x03\x07\x03\x15\x03\x17\x03\x1c\x03%\x030\x033\x03<\x03E\x03N\x03S\x03\\\x03g\x03j\x03w\x03\x80\x03\x8d\x03\x9f\x03\xa4\x03\xa7\x03\xac\x00\x00\x00\x00\x00\x00\x02\x01\x00\x00\x00\x00\x00\x00\x00\x82\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\xae

**Comment by wooster** [comment]
@paulr4 Any chance you could attach the plist as a file here?

**Comment by paulr4** [comment]
Sure, here:

[plistfile.zip](https://github.com/wooster/biplist/files/1317616/plistfile.zip)

**Comment by wooster** [comment]
Oh. That file looks like it was printed in a Python interactive session. Those sequences like "\xae" are replacing the actual binary contents.

Do you have the original file generated by the program?

**Comment by paulr4** [comment]
No, sorry, it was embedded in an SQLite file and I read it directly into Python variable from there. I wrote it to a file using plistfile.write(str(plist)), I guess that was my mistake. What should I have done?

**Comment by paulr4** [comment]
I think I've got it - open the output file in binary mode ('wb') and write using bytes():

plistfile = open('tempfile','wb')
plistfile.write(bytes(plist))

**Comment by paulr4** [comment]
Unfortunately I still can't get anything useful out of the file.

[plistfile.zip](https://github.com/wooster/biplist/files/1321025/plistfile.zip)

I've tried every combination of BinaryPlist, readPlist, and Parse I can think of, trying to adapt the examples given [here](https://github.com/google/binplist/blob/master/binplist/binplist.py), but no luck so far sadly.

**Comment by wooster** [comment]
Google's binplist project isn't the same as my biplist project.

If you're reading from a file on the filesystem, you can do something like:

```python
>>> import biplist 
>>> biplist.readPlist("/Users/andrew/Downloads/plistfile_new.plist")
{'$objects': ['$null', {'NS.keys': [Uid(2), Uid(4), Uid(6), Uid(8)], 'NS.objects': [Uid(10), Uid(12), Uid(14), Uid(16)], '$class': Uid(18)}, {'$class': Uid(3), 'NS.string': 'fullname'}, {'$classes': ['NSString', 'NSObject'], '$classname': 'NSString'}, {'$class': Uid(5), 'NS.string': 'address'}, {'$classes': ['NSString', 'NSObject'], '$classname': 'NSString'}, {'$class': Uid(7), 'NS.string': 'phone'}, {'$classes': ['NSString', 'NSObject'], '$classname': 'NSString'}, {'$class': Uid(9), 'NS.string': 'email'}, {'$classes': ['NSString', 'NSObject'], '$classname': 'NSString'}, {'$class': Uid(11), 'NS.string': 'Test Client'}, {'$classes': ['NSString', 'NSObject'], '$classname': 'NSString'}, {'$class': Uid(13), 'NS.string': '123 ABC Street'}, {'$classes': ['NSString', 'NSObject'], '$classname': 'NSString'}, {'$class': Uid(15), 'NS.string': '1234'}, {'$classes': ['NSString', 'NSObject'], '$classname': 'NSString'}, {'$class': Uid(17), 'NS.string': 'test@test.com'}, {'$classes': ['NSString', 'NSObject'], '$classname': 'NSString'}, {'$classes': ['NSDictionary', 'NSObject'], '$classname': 'NSDictionary'}], '$archiver': 'NSKeyedArchiver', '$version': 100000, '$top': {'root': Uid(1)}}
```

If you're reading from SQLite into a variable, you can use `StringIO` to turn that variable into a file-like object and read from there:

```python
>>> import StringIO
>>> contents = open("plistfile.plist").read()
>>> file_like_object = StringIO.StringIO(contents)
>>> biplist.readPlist(file_like_object)
{'$objects': ['$null', {'NS.keys': [Uid(2), Uid(4), Uid(6), Uid(8)], 'NS.objects': [Uid(10), Uid(12), Uid(14), Uid(16)], '$class': Uid(18)}, {'$class': Uid(3), 'NS.string': 'fullname'}, {'$classes': ['NSString', 'NSObject'], '$classname': 'NSString'}, {'$class': Uid(5), 'NS.string': 'address'}, {'$classes': ['NSString', 'NSObject'], '$classname': 'NSString'}, {'$class': Uid(7), 'NS.string': 'phone'}, {'$classes': ['NSString', 'NSObject'], '$classname': 'NSString'}, {'$class': Uid(9), 'NS.string': 'email'}, {'$classes': ['NSString', 'NSObject'], '$classname': 'NSString'}, {'$class': Uid(11), 'NS.string': 'Test Client'}, {'$classes': ['NSString', 'NSObject'], '$classname': 'NSString'}, {'$class': Uid(13), 'NS.string': '123 ABC Street'}, {'$classes': ['NSString', 'NSObject'], '$classname': 'NSString'}, {'$class': Uid(15), 'NS.string': '1234'}, {'$classes': ['NSString', 'NSObject'], '$classname': 'NSString'}, {'$class': Uid(17), 'NS.string': 'test@test.com'}, {'$classes': ['NSString', 'NSObject'], '$classname': 'NSString'}, {'$classes': ['NSDictionary', 'NSObject'], '$classname': 'NSDictionary'}], '$archiver': 'NSKeyedArchiver', '$version': 100000, '$top': {'root': Uid(1)}}
```

This particular plist is a keyed archive, used by the program to encode an object in memory. The format can be fairly opaque to decode.

If you're on OS X, you can use the Foundation bindings to more easily process the file, eg:

```python
>>> import Foundation
>>> data = Foundation.NSData.dataWithContentsOfFile_("plistfile.plist")
>>> Foundation.NSKeyedUnarchiver.unarchiveObjectWithData_(data)
{
    address = "123 ABC Street";
    email = "test@test.com";
    fullname = "Test Client";
    phone = 1234;
}
```

**Comment by paulr4** [comment]
Thank you for your help! I finally implemented this with the following code, where ClientDetails contains the impenetrable raw plist data:

```
import io
import biplist
tmp = io.BytesIO()
tmp.write(ClientDetails)
plist = biplist.readPlist(tmp)
tmp.close()
```
'plist' then contained a complicated nested arrangement of variables, which could at least be rooted through using usual python methods.
